### ISSUE TITLE
Make Summary copy email-friendly

### ISSUE THREAD

**Issue by anater** [juanparadox/qubicle#11]
We use the 'Copy to Clipboard' to avoid writing the same basic email over and over so it should be formatted more like an email we'd send without making any edits.

**Comment by anater** [comment]
_Example:_

Hey team,
 
Here are the updates from our code review (between MM/DD/YYYY & MM/DD/YYYY)
 
Total Issues: 1,916
Blocker: 0 (0)
Critical: 3 (-13)
Major: 125 (-218)
Minor: 1,788 (-689)
 
Looks like there were major reductions in issues in the past few weeks. Great work, team!

**Comment by juanparadox** [comment]
I'll be looking into this tomorrow!

**Comment by juanparadox** [comment]
This will be updated for the next code review exercise.

**Comment by anater** [comment]
You still working on this @juanparadox? Or should I try to tackle it?
